import { styled } from '@/styles'
import Head from 'next/head'

const Button = styled('button', {
  backgroundColor: '$green300',
})

export default function Home() {
  return (
    <>
      <Head>
        <title>😎 Pedroca Shop 😎</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Hello Word 😎</Button>
    </>
  )
}
